리스너(Euphony) 함수 추가 및 MainActivity에 onClickListener 추가
euphony-io/check-in-listener pull request #8
Opened 2021-09-17 15:54 UTC by YoungSeokHong

>죄송합니다 생각보다 CMake에 오래 잡혀있느라 PR이 늦었네요ㅠㅠ

우선 진산님하고 만들기로 한 리스너를 만들기 위해서 버튼을 받아오는 onClickListener를 만들고 listener()함수를 viewModel에 만들었습니다. 코틀린도 처음이고 mvvm 모델도 처음이라 맞게 한건지 모르겠네요ㅠㅠ 혹독한 피드백 부탁드립니다!

2021-09-17 16:43 UTC, Jsueeee commented
우선 첫 pr이네요! 넘넘 수고하셨습니다!

2021-09-17 16:45 UTC, Jsueeee commented
코틀린이 처음이라고 하셔서요! 피드백을 드리자면 코틀린은 함수형 프로그래밍 언어이기 때문에 자바보다 훨씬 간결하게 코드를 짤 수 있습니다! 이게 코틀린의 장점이죠!! MainActivity에 새로 추가하신 모든 초록색 코드 대신에

2021-09-17 16:52 UTC, Jsueeee requested changes

2021-09-17 16:52 UTC, Jsueeee commented on app/src/main/java/com/android/check_in_listener/MainActivity.kt
> +
```suggestion
binding.btnListen.setOnClickListener { model.listener() }
```

2021-09-17 16:52 UTC, Jsueeee commented on app/src/main/java/com/android/check_in_listener/MainActivity.kt
> +
코틀린이 처음이라고 하셔서요! 피드백을 드리자면 코틀린은 함수형 프로그래밍 언어이기 때문에 자바보다 훨씬 간결하게 코드를 짤 수 있습니다! 이게 코틀린의 장점이죠!! MainActivity에 새로 추가하신 모든 초록색 코드 대신에 이 한줄로 표현할 수 있습니다!

2021-09-17 17:14 UTC, YoungSeokHong commented on app/src/main/java/com/android/check_in_listener/MainActivity.kt
> +
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 코틀린은 자비가 없군요. 감사합니다!

2021-09-17 23:31 UTC, designe commented on app/src/main/java/com/android/check_in_listener/MainActivity.kt
> +
ㅎㅎ 코틀린은 언어 패러다임 연구하시는 분들도 객체지향과 함수형을 잘 섞었다고 많이들 좋아하시더라구요.

2021-09-18 01:42 UTC, sujin9 approved these changes
저도 코틀린이 처음이라 저렇게 한 줄로 표현이 가능한지 몰랐네요..!
배우고 갑니당 감사해요 ㅎㅎ

2021-09-18 03:14 UTC, dlwlstks96 commented
고생하셨습니다!! mvvm 패턴 공부해봤는데 왜 어렵다 하셨는지 알았습니다ㅠ
만들어주신 listener 함수 내에서 EuRxManager 객체 생성하고 listener 설정 및 음파 수신하게끔 진행하면 되는 것 맞을까요??
@YoungSeokHong

2021-09-18 03:14 UTC, dlwlstks96 approved these changes

2021-09-18 04:58 UTC, eunzinn approved these changes
저도 코틀린이 처음인데 쉬운듯 하면서 어렵네요..! 고생하셨씁니다!!!

2021-09-18 05:46 UTC, YoungSeokHong commented
> 고생하셨습니다!! mvvm 패턴 공부해봤는데 왜 어렵다 하셨는지 알았습니다ㅠ
> 만들어주신 listener 함수 내에서 EuRxManager 객체 생성하고 listener 설정 및 음파 수신하게끔 진행하면 되는 것 맞을까요??
> @YoungSeokHong

네넵 찾아보니까 대부분의 정보처리는 VeiwModel에서 일어나는 것 같아서 MainViewModel에 있는 listener함수를 사용하시면 될 것 같습니다!

2021-09-18 05:46 UTC, merged